// Code generated by "esc -o ./resources/RESOURCES.go -pkg resources ./resources/source"; DO NOT EDIT.

package resources

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/resources/source/userdata.sh": {
		local:   "resources/source/userdata.sh",
		size:    1851,
		modtime: 1517200951,
		compressed: `
H4sIAAAAAAAC/7RVX2/bNhB/56e42n3YsEmyk9RADGiAU6RbMOQP7HTAUBTGmTxLRCSSII+O3dTffZCs
pnYW72n1C33/fzz+7tR/ky20yRYYSkjWJGZ3k+n9ZH57ffn7ZH5xdTOZ/j2/m9z/kWelrSmLi2g4Zk9P
6cyhZ7zQBv3mBmvaboXo/88/0Rd9uKfApMAa+NgWh+EoHZy1psn11Rg6SLrGgkJWruokBNUBTdZkNFZJ
G5JgrUZnSSC/Ip+cDIajwbvhKB3CT1jrZDBanJ+NRqOfhV7CJ3gDyRJ6B5eOgbxCxjSUPfgsuCQjAGT0
FSSrACWzG2fZcHSenrw7S7szq5ApcBucNNGQWDiWtklX1lbBL+vjPkstRB+uTGCsKqAV+Q2X2hSiuZiW
BCG65l+wHgJbJ9BxUhBDdAqZINnsaQqP6kClu7x7SfAxyEpDNF+0g0Jz4/4Dnhpuowf7aGDRckrgY4Bw
CtJBOB1n2dMTpLPTiygfiGG77eQ/aQPb7WGz0LlKS2RtTfpFO7ED/rLtL7wgUQd28fwQb4+NxA9pwuzj
3eX0r6vZ7VT0YXr5YfyNV98fRKXWF5now/uK0NjIEEhao9BvQGlPkq3fiPpBaQ+JW0FGLPfCM2nNMlXi
cNS/152/v735kPc+OW8Lj/U4tINuayrws5C2rtGo/GhTWrizdsSEibXzVoZ8KJ5x5RnXTjivrde8yc/P
zwVGtoHRc84+Uit62imiobUjyaREqwjUZBvsBE/sNYX8VNBas7SKQj749UQ0pA+6MFjl95fT61Z+RL0X
bB2Gwtvo8iVWgcSDrqpDTTNweceEwMpGnle2WOqK8myFPqtske01Jq1s8cJvXuN6sWEK+fD64qVtgfIh
ug5Na5HoOPrXo2hFhsOcDC4qUh1CT7uezgMr8r7T7oRnrPsQyftvMPdc/lVw33YIs7Ecg9nYXoXZEyRL
C723/8W2Hvx2hKUHTW5Uze67Q5YlRAdc0h7jZdlsj2TafRHGu+NwqpsJa7gTHcyea722OTsGwtev8Ope
Rc//BAAA///H6417OwcAAA==
`,
	},

	"/": {
		isDir: true,
		local: "",
	},

	"/resources": {
		isDir: true,
		local: "resources",
	},

	"/resources/source": {
		isDir: true,
		local: "resources/source",
	},
}
