// Code generated by "esc -o ./resources/RESOURCES.go -pkg resources ./resources/source"; DO NOT EDIT.

package resources

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/resources/source/userdata.sh": {
		local:   "resources/source/userdata.sh",
		size:    1849,
		modtime: 1517163284,
		compressed: `
H4sIAAAAAAAC/7RVX2/bNhB/56e42n3YsEmyk9RADGiAU6RbMKQJ7HTAUBTGmTxLRCSSII+O3TbffZCs
plYW72n1C33/fzz+7jR8la20yVYYSki2JBa3s/ndbHlzffn7bHlx9X42/3t5O7v7I89KW1MWV9FwzBYO
PWNaYb1SmGKtJmdCDP/nnxiKIdxRYFJgDXxoS8N4ko7OWtPs+moKHSBdY0EhKzd1EoLqYCZbMhqrpA1J
WpRJIL8hn5yMxpPRm/EkHcNPWOtkNFmdn00mk5+FXsNHeAXJGga9K8dAXiFjGsoBfBJckhEAMvoKkk2A
ktlNs2w8OU9P3pyl3ZlVyBS4DU6aaEgsHEvbpCtrq+CX7XGftRZiCFcmMFYV0Ib8jkttCtFcTEuCEF3z
L1gPga0T6DgpiCE6hUyQ7A40hUfVU+ku70ESfAiy0hDNZ+2g0Ny4/4CnhpvowT4YWGmDfifwIUA4Bekg
nE6z7MsXSBenF1HeE8PjYyf/STt4fOw3C52rtETW1qSftRN74M/b/swLEtWzi6eHeH1sIH5IExYfbi/n
f10tbuZiCPPLd9NvvPr+ICq1vsjEEN5WhMZGhkDSGoV+B0p7kmz9TtT3SntI3AYyYnkQnklr1qkS/UH/
Xnf59ub9u3zw0XlbeKynoZ10W1OBn4S0dY1G5Ueb0sJdtCMmTKydtzLkY/GEK8+4dsJ5bb3mXX5+fi4w
sg2MnnP2kVrR014RDW0dSSYlWkWgJttoL3hirynkp4K2mqVVFPLRryeiIX3QhcEqv7ucX7fyA+qDYOsw
FN5Gl6+xCiTudVX1Nc3A5R0TAisbeVnZYq0ryrMN+qyyRXbQmLSyxTO/ZY3b1Y4p5OPri+e2Fcr76Do0
rUWi4+hfjqINGQ5LMriqSHUIPe17ugysyPtOuxeesB5CJO+/wTxw+VfBQ1sfZmM5BrOxvQhzIEiWFgav
/4ttA/jtCEt7TW5Uze67RZYlRAdc0gHjZdlsj2TefRGm+6M/1c2ENdyJDhZPtV7anB0D4etXeHGvoud/
AgAA///6mHEXOQcAAA==
`,
	},

	"/": {
		isDir: true,
		local: "",
	},

	"/resources": {
		isDir: true,
		local: "resources",
	},

	"/resources/source": {
		isDir: true,
		local: "resources/source",
	},
}
